'use strict';

/**
 * GF-016 — Semântica canónica Ishikawa / Root Cause Investigation.
 * SSOT — Signal Loader / runtime DEVEM importar daqui (GF-017+).
 */

const ISHIKAWA_INVESTIGATION_STATUS = Object.freeze({
  DRAFT: 'DRAFT',
  UNDER_INVESTIGATION: 'UNDER_INVESTIGATION',
  ROOT_CAUSE_DEFINED: 'ROOT_CAUSE_DEFINED',
  ACTIONS_DEFINED: 'ACTIONS_DEFINED',
  UNDER_APPROVAL: 'UNDER_APPROVAL',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  CLOSED: 'CLOSED',
  ARCHIVED: 'ARCHIVED'
});

const ISHIKAWA_INVESTIGATION_STATUS_LIST = Object.freeze(Object.values(ISHIKAWA_INVESTIGATION_STATUS));

const ISHIKAWA_WORKFLOW_STAGE = Object.freeze({
  DRAFT: 'DRAFT',
  INVESTIGATION: 'INVESTIGATION',
  ROOT_CAUSE_DEFINITION: 'ROOT_CAUSE_DEFINITION',
  ACTION_PLANNING: 'ACTION_PLANNING',
  APPROVAL: 'APPROVAL',
  CLOSURE: 'CLOSURE',
  ARCHIVE: 'ARCHIVE'
});

const ISHIKAWA_WORKFLOW_STAGE_LIST = Object.freeze(Object.values(ISHIKAWA_WORKFLOW_STAGE));

const ISHIKAWA_WORKFLOW_ACTION = Object.freeze({
  START: 'start',
  DEFINE_ROOT_CAUSE: 'define_root_cause',
  PLAN_ACTIONS: 'plan_actions',
  SUBMIT_APPROVAL: 'submit_approval',
  APPROVE: 'approve',
  REJECT: 'reject',
  REOPEN: 'reopen',
  CLOSE: 'close',
  ARCHIVE: 'archive'
});

const ISHIKAWA_WORKFLOW_TRANSITIONS = Object.freeze({
  [`${ISHIKAWA_WORKFLOW_STAGE.DRAFT}:${ISHIKAWA_WORKFLOW_ACTION.START}`]: {
    next_stage: ISHIKAWA_WORKFLOW_STAGE.INVESTIGATION,
    status: ISHIKAWA_INVESTIGATION_STATUS.UNDER_INVESTIGATION
  },
  [`${ISHIKAWA_WORKFLOW_STAGE.INVESTIGATION}:${ISHIKAWA_WORKFLOW_ACTION.DEFINE_ROOT_CAUSE}`]: {
    next_stage: ISHIKAWA_WORKFLOW_STAGE.ROOT_CAUSE_DEFINITION,
    status: ISHIKAWA_INVESTIGATION_STATUS.ROOT_CAUSE_DEFINED
  },
  [`${ISHIKAWA_WORKFLOW_STAGE.ROOT_CAUSE_DEFINITION}:${ISHIKAWA_WORKFLOW_ACTION.PLAN_ACTIONS}`]: {
    next_stage: ISHIKAWA_WORKFLOW_STAGE.ACTION_PLANNING,
    status: ISHIKAWA_INVESTIGATION_STATUS.ACTIONS_DEFINED
  },
  [`${ISHIKAWA_WORKFLOW_STAGE.ACTION_PLANNING}:${ISHIKAWA_WORKFLOW_ACTION.SUBMIT_APPROVAL}`]: {
    next_stage: ISHIKAWA_WORKFLOW_STAGE.APPROVAL,
    status: ISHIKAWA_INVESTIGATION_STATUS.UNDER_APPROVAL
  },
  [`${ISHIKAWA_WORKFLOW_STAGE.APPROVAL}:${ISHIKAWA_WORKFLOW_ACTION.APPROVE}`]: {
    next_stage: ISHIKAWA_WORKFLOW_STAGE.CLOSURE,
    status: ISHIKAWA_INVESTIGATION_STATUS.APPROVED
  },
  [`${ISHIKAWA_WORKFLOW_STAGE.CLOSURE}:${ISHIKAWA_WORKFLOW_ACTION.CLOSE}`]: {
    next_stage: ISHIKAWA_WORKFLOW_STAGE.CLOSURE,
    status: ISHIKAWA_INVESTIGATION_STATUS.CLOSED
  },
  [`${ISHIKAWA_WORKFLOW_STAGE.CLOSURE}:${ISHIKAWA_WORKFLOW_ACTION.ARCHIVE}`]: {
    next_stage: ISHIKAWA_WORKFLOW_STAGE.ARCHIVE,
    status: ISHIKAWA_INVESTIGATION_STATUS.ARCHIVED
  },
  [`${ISHIKAWA_WORKFLOW_STAGE.INVESTIGATION}:${ISHIKAWA_WORKFLOW_ACTION.REJECT}`]: {
    next_stage: ISHIKAWA_WORKFLOW_STAGE.DRAFT,
    status: ISHIKAWA_INVESTIGATION_STATUS.REJECTED
  },
  [`${ISHIKAWA_WORKFLOW_STAGE.ROOT_CAUSE_DEFINITION}:${ISHIKAWA_WORKFLOW_ACTION.REJECT}`]: {
    next_stage: ISHIKAWA_WORKFLOW_STAGE.DRAFT,
    status: ISHIKAWA_INVESTIGATION_STATUS.REJECTED
  },
  [`${ISHIKAWA_WORKFLOW_STAGE.ACTION_PLANNING}:${ISHIKAWA_WORKFLOW_ACTION.REJECT}`]: {
    next_stage: ISHIKAWA_WORKFLOW_STAGE.DRAFT,
    status: ISHIKAWA_INVESTIGATION_STATUS.REJECTED
  },
  [`${ISHIKAWA_WORKFLOW_STAGE.APPROVAL}:${ISHIKAWA_WORKFLOW_ACTION.REJECT}`]: {
    next_stage: ISHIKAWA_WORKFLOW_STAGE.DRAFT,
    status: ISHIKAWA_INVESTIGATION_STATUS.REJECTED
  },
  [`${ISHIKAWA_WORKFLOW_STAGE.DRAFT}:${ISHIKAWA_WORKFLOW_ACTION.REOPEN}`]: {
    next_stage: ISHIKAWA_WORKFLOW_STAGE.DRAFT,
    status: ISHIKAWA_INVESTIGATION_STATUS.DRAFT
  }
});

const ISHIKAWA_INTEGRATION_REFS = Object.freeze([
  'quality_inspection_id',
  'ncr_workflow_instance_id',
  'capa_workflow_instance_id',
  'ppap_submission_id',
  'msa_study_id',
  'supplier_ref',
  'part_ref'
]);

function isValidInvestigationStatus(s) {
  return ISHIKAWA_INVESTIGATION_STATUS_LIST.includes(String(s || '').toUpperCase());
}

function isValidWorkflowStage(s) {
  return ISHIKAWA_WORKFLOW_STAGE_LIST.includes(String(s || '').toUpperCase());
}

function resolveTransition(workflowStage, action) {
  const key = `${String(workflowStage).toUpperCase()}:${String(action).toLowerCase()}`;
  return ISHIKAWA_WORKFLOW_TRANSITIONS[key] || null;
}

function initialInvestigationState() {
  return {
    status: ISHIKAWA_INVESTIGATION_STATUS.DRAFT,
    workflow_stage: ISHIKAWA_WORKFLOW_STAGE.DRAFT
  };
}

module.exports = {
  ISHIKAWA_INVESTIGATION_STATUS,
  ISHIKAWA_INVESTIGATION_STATUS_LIST,
  ISHIKAWA_WORKFLOW_STAGE,
  ISHIKAWA_WORKFLOW_STAGE_LIST,
  ISHIKAWA_WORKFLOW_ACTION,
  ISHIKAWA_WORKFLOW_TRANSITIONS,
  ISHIKAWA_INTEGRATION_REFS,
  isValidInvestigationStatus,
  isValidWorkflowStage,
  resolveTransition,
  initialInvestigationState
};
