const express = require('express');
const router = express.Router();
const proacao = require('../services/proacao');
const { isValidUUID } = require('../utils/security');

router.post('/', async (req,res)=>{ try{ const payload = { ...req.body, company_id: req.user.company_id }; const p = await proacao.createProposal(payload); res.json({ ok:true, proposal: p }); }catch(err){ console.error(err); res.status(500).json({ ok:false, error: err.message }); }});
router.get('/', async (req,res)=>{ try{ const list = await proacao.listProposals(200, req.user.company_id); res.json({ ok:true, proposals: list }); }catch(err){ console.error(err); res.status(500).json({ ok:false, error: err.message }); }});
router.get('/:id', async (req,res)=>{ try{ if (!isValidUUID(req.params.id)) return res.status(400).json({ ok: false, error: 'ID inválido' }); const p = await proacao.getProposal(req.params.id, req.user.company_id); if(!p) return res.status(404).json({ ok:false, error:'not found' }); res.json({ ok:true, proposal: p }); }catch(err){ console.error(err); res.status(500).json({ ok:false, error: err.message }); }});
router.post('/:id/evaluate', async (req,res)=>{ try{ if (!isValidUUID(req.params.id)) return res.status(400).json({ ok: false, error: 'ID inválido' }); const ev = await proacao.aiEvaluateProposal(req.params.id, req.user.company_id); res.json({ ok:true, evaluation: ev }); }catch(err){ console.error(err); res.status(500).json({ ok:false, error: err.message }); }});
router.post('/:id/escalate', async (req,res)=>{ try{ if (!isValidUUID(req.params.id)) return res.status(400).json({ ok: false, error: 'ID inválido' }); await proacao.escalateToProjects(req.params.id, req.body.comment, req.body.escalated_by, req.user.company_id); res.json({ ok:true }); }catch(err){ console.error(err); res.status(500).json({ ok:false, error: err.message }); }});
router.post('/:id/assign', async (req,res)=>{ try{ if (!isValidUUID(req.params.id)) return res.status(400).json({ ok: false, error: 'ID inválido' }); await proacao.assignToAdministrative(req.params.id, req.body.admin_sector, req.body.assigned_by, req.body.team, req.user.company_id); res.json({ ok:true }); }catch(err){ console.error(err); res.status(500).json({ ok:false, error: err.message }); }});
router.post('/:id/record', async (req,res)=>{ try{ if (!isValidUUID(req.params.id)) return res.status(400).json({ ok: false, error: 'ID inválido' }); await proacao.recordPhaseData(req.params.id, req.body.phaseNumber, req.body.collectedData, req.body.userId, req.user.company_id); res.json({ ok:true }); }catch(err){ console.error(err); res.status(500).json({ ok:false, error: err.message }); }});
router.post('/:id/finalize', async (req,res)=>{ try{ if (!isValidUUID(req.params.id)) return res.status(400).json({ ok: false, error: 'ID inválido' }); await proacao.finalizeProposal(req.params.id, req.body.finalReport, req.body.closedBy, req.user.company_id); res.json({ ok:true }); }catch(err){ console.error(err); res.status(500).json({ ok:false, error: err.message }); }});

module.exports = router;
