'use strict';

module.exports = {
  CONTRACT_VERSION: 5,
  DOMAIN_ID: 'environment',
  LAYERS: Object.freeze(['operations', 'governance', 'telemetry', 'cognitive', 'executive']),
  TELEMETRY_API_PREFIX: '/api/environment-telemetry',
  COGNITIVE_API_PREFIX: '/api/environment-cognitive',
  EXECUTIVE_API_PREFIX: '/api/environment-executive',
  EVENTS: Object.freeze([
    'environment.emission.snapshot',
    'environment.effluent.analysis',
    'environment.waste.trace',
    'environment.water.sample_collected',
    'environment.water.threshold_exceeded',
    'environment.effluent.analysis_completed',
    'environment.emission.alert_triggered',
    'environment.waste.manifest_created',
    'environment.field.occurrence_registered',
    'environment.environmental.incident_opened',
    'environment.environmental.evidence_attached',
    'environment.offline.sync_started',
    'environment.offline.sync_completed',
    'environment.scan.performed',
    'environment.mobile.sync_completed',
    'environment.telemetry.sample_ingested',
    'environment.telemetry.edge_synced',
    'environment.telemetry.threshold_exceeded',
    'environment.telemetry.drift_detected',
    'environment.telemetry.anomaly_detected',
    'environment.telemetry.device_disconnected',
    'environment.telemetry.reconnect_completed',
    'environment.telemetry.normalization_failed',
    'environment.cognitive.risk_predicted',
    'environment.cognitive.drift_detected',
    'environment.cognitive.trend_detected',
    'environment.cognitive.overflow_risk',
    'environment.cognitive.excess_emission_risk',
    'environment.cognitive.recommendation_generated',
    'environment.cognitive.reasoning_generated',
    'environment.cognitive.environmental_narrative_generated',
    'environment.cognitive.cross_domain_correlation_detected',
    'environment.executive.esg_insight_generated',
    'environment.executive.sustainability_insight_generated',
    'environment.executive.carbon_hotspot_detected',
    'environment.executive.environmental_risk_escalated',
    'environment.executive.maturity_shift_detected',
    'environment.executive.environmental_narrative_generated',
    'environment.executive.cross_domain_insight_generated'
  ]),
  BOUNDED_CONTEXTS: Object.freeze(['quality', 'safety', 'logistics', 'production', 'utilities', 'energy'])
};
