'use strict';

const CONTRACT_VERSION = 7;

const EVENTS = [
  'quality.ncr.opened',
  'quality.ncr.closed',
  'quality.capa.created',
  'quality.capa.verified',
  'quality.capa.extended',
  'quality.spc.sample_recorded',
  'quality.spc.violation_detected',
  'quality.capa.risk_escalated',
  'quality.supplier.score_changed',
  'quality.audit.reconstructed',
  'quality.executive.insight_generated',
  'quality.risk.threshold_exceeded',
  'quality.analytics.pattern_detected',
  'quality.inspection.started',
  'quality.inspection.saved',
  'quality.inspection.completed',
  'quality.inspection.failed',
  'quality.evidence.attached',
  'quality.offline.sync_started',
  'quality.offline.sync_completed',
  'quality.scan.performed',
  'quality.kiosk.session_started',
  'quality.kiosk.session_closed',
  'quality.anomaly.detected',
  'quality.supplier.deviated',
  'quality.calibration.expired',
  'quality.process.drift_detected',
  'quality.audit.completed',
  'quality.risk.escalated',
  'quality.risk.acknowledged',
  'quality.pdca.phase_advanced',
  'quality.pdca.closed',
  'quality.workflow.transition',
  'quality.workflow.approved',
  'quality.workflow.rejected',
  'quality.workflow.resubmitted',
  'quality.cognitive.operational_hint',
  'quality.cognitive.governance_analysis',
  'quality.telemetry.sample_ingested',
  'quality.telemetry.batch_ingested',
  'quality.telemetry.range_breached',
  'quality.cognitive.drift_predicted',
  'quality.cognitive.recurrence_detected',
  'quality.cognitive.supplier_score_changed',
  'quality.cognitive.anomaly_predicted',
  'quality.cognitive.process_deterioration_detected',
  'quality.cognitive.recommendation_generated',
  'quality.cognitive.executive_insight_generated',
  'quality.cognitive.risk_escalated',
  'quality.cognitive.pattern_detected',
  'quality.rollout.tenant_stage_changed',
  'quality.rollout.plant_stage_changed',
  'quality.rollout.workflow_enabled',
  'quality.rollout.readiness_blocked',
  'quality.rollout.maturity_changed',
  'quality.rollout.saturation_detected',
  'quality.rollout.recommendation_suppressed',
  'quality.rollout.cognitive_ready',
  'quality.rollout.activation_approved'
];

module.exports = {
  CONTRACT_VERSION,
  DOMAIN_ID: 'quality',
  EVENTS,
  RUNTIME_FLAG: 'IMPETUS_QUALITY_UNIVERSAL_RUNTIME_ENABLED',
  INTERNAL_API_PREFIX: '/api/internal/quality-universal',
  OPERATIONAL_UX_FLAG: 'IMPETUS_QUALITY_OPERATIONAL_RUNTIME_ENABLED',
  OPERATIONAL_API_PREFIX: '/api/quality-operational',
  GOVERNANCE_RUNTIME_FLAG: 'IMPETUS_QUALITY_GOVERNANCE_RUNTIME_ENABLED',
  GOVERNANCE_API_PREFIX: '/api/quality-governance',
  TELEMETRY_RUNTIME_FLAG: 'IMPETUS_QUALITY_TELEMETRY_RUNTIME_ENABLED',
  TELEMETRY_API_PREFIX: '/api/quality-telemetry',
  COGNITIVE_RUNTIME_FLAG: 'IMPETUS_QUALITY_COGNITIVE_RUNTIME_ENABLED',
  COGNITIVE_API_PREFIX: '/api/quality-cognitive',
  ROLLOUT_RUNTIME_FLAG: 'IMPETUS_QUALITY_ROLLOUT_RUNTIME_ENABLED',
  ROLLOUT_API_PREFIX: '/api/quality-rollout'
};